import type { Config } from 'tailwindcss';

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        forest: {
          50: 'var(--color-forest-50)',
          100: 'var(--color-forest-100)',
          200: 'var(--color-forest-200)',
          300: 'var(--color-forest-300)',
          400: 'var(--color-forest-400)',
          500: 'var(--color-forest-500)',
          600: 'var(--color-forest-600)',
          700: 'var(--color-forest-700)',
          800: 'var(--color-forest-800)',
          900: 'var(--color-forest-900)',
        },
        water: {
          50: 'var(--color-water-50)',
          100: 'var(--color-water-100)',
          200: 'var(--color-water-200)',
          300: 'var(--color-water-300)',
          400: 'var(--color-water-400)',
          500: 'var(--color-water-500)',
          600: 'var(--color-water-600)',
          700: 'var(--color-water-700)',
          800: 'var(--color-water-800)',
          900: 'var(--color-water-900)',
        },
        earth: {
          50: 'var(--color-earth-50)',
          100: 'var(--color-earth-100)',
          200: 'var(--color-earth-200)',
          300: 'var(--color-earth-300)',
          400: 'var(--color-earth-400)',
          500: 'var(--color-earth-500)',
          600: 'var(--color-earth-600)',
          700: 'var(--color-earth-700)',
          800: 'var(--color-earth-800)',
          900: 'var(--color-earth-900)',
        },
        ink: {
          50: 'var(--color-ink-50)',
          100: 'var(--color-ink-100)',
          200: 'var(--color-ink-200)',
          300: 'var(--color-ink-300)',
          400: 'var(--color-ink-400)',
          500: 'var(--color-ink-500)',
          600: 'var(--color-ink-600)',
          700: 'var(--color-ink-700)',
          800: 'var(--color-ink-800)',
          900: 'var(--color-ink-900)',
        },
        accent: 'var(--color-accent)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        success: 'var(--color-success)',
        bg: {
          base: 'var(--color-bg-base)',
          surface: 'var(--color-bg-surface)',
          raised: 'var(--color-bg-raised)',
          overlay: 'var(--color-bg-overlay)',
        },
        text: {
          primary: 'var(--color-text-primary)',
          secondary: 'var(--color-text-secondary)',
          muted: 'var(--color-text-muted)',
          inverse: 'var(--color-text-inverse)',
        },
        border: {
          subtle: 'var(--color-border-subtle)',
          DEFAULT: 'var(--color-border)',
          strong: 'var(--color-border-strong)',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        DEFAULT: 'var(--radius-md)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      boxShadow: {
        sm: 'var(--shadow-sm)',
        DEFAULT: 'var(--shadow-md)',
        md: 'var(--shadow-md)',
        lg: 'var(--shadow-lg)',
        xl: 'var(--shadow-xl)',
      },
      transitionDuration: {
        fast: 'var(--transition-fast)',
        DEFAULT: 'var(--transition-base)',
        slow: 'var(--transition-slow)',
      },
    },
  },
  plugins: [],
} satisfies Config;
